name: Hugo Deploy

# 只监听 source 分支的改动
on:
  push:
    branches:
      - source

# 自定义环境变量
env:
  POST_ASSET_IMAGE_CDN: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 获取博客源码和主题
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0


      #- name: Copy theme config
        #env:
          #GITALK_SECERT: ${{ secrets.GITALK_SECERT }}
        #run: |
          #sed -i "s/{SECRET}/$GITALK_SECERT/" _config.even.yml
          #cp _config.even.yml themes/even/_config.yml
      ## 这里用的是 Node.js 14.x
      #- name: Set up Node.js 
        #uses: actions/setup-node@v2
        #with:
          #node-version: '14'
          #cache: 'npm'

      #- name: Cache npm dependencies
        #uses: actions/cache@v2
        #with:
          #path: '~/.npm'
          #key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          #restore-keys: |
            #${{ runner.os }}-node-

      # 安装依赖
      #- name: Install dependencies
        #run: |
          #npm install
          
      # 从之前设置的 secret 获取部署私钥
      - name: Set up environment
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
          # extended: true 

      - name: Cache Hugo Modules 
        uses: actions/cache@v2
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Build
        run: hugo --minify

      - name: Create CNAME file
        run: echo 'blog.d0zingcat.dev' > public/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/source' }}
        with:
          github_token: ${{ secrets.PAGES_TOKEN }}
          publish_dir: ./public
          publish_branch: main
